plugins {
    id 'java'
    id 'pmd'
    id 'checkstyle'
}

group = 'sports.bets'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    implementation 'org.apache.commons:commons-lang3:3.20.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

checkstyle {
    toolVersion = "13.2.0"
    ignoreFailures = false
    configDirectory = file("${project.rootDir}/checkstyle")
    configFile = file("${project.rootDir}/checkstyle/checkstyle.xml")
}

pmd {
    ignoreFailures = false
    consoleOutput = true
    toolVersion = "7.16.0"
    rulesMinimumPriority = 5
    ruleSets = ["category/java/errorprone.xml", "category/java/bestpractices.xml"]
}